//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IhbiREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumable
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public int fruit { get; set; }
        public int calcium { get; set; }
        public int vegetable { get; set; }
        public int water { get; set; }
    }
}
