//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IhbiREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise2
    {
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> stretching { get; set; }
        public Nullable<int> pelvic { get; set; }
        public Nullable<int> minutes { get; set; }
        public string type { get; set; }
    }
}
