//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IhbiREST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ihbiprojectDBEntities : DbContext
    {
        public ihbiprojectDBEntities()
            : base("name=ihbiprojectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consumable> Consumables { get; set; }
        public virtual DbSet<Conusmable_Type> Conusmable_Type { get; set; }
        public virtual DbSet<Exercise_Type> Exercise_Type { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Welness> Welnesses { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Exercise2> Exercise2 { get; set; }
    }
}
