//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IhbiREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Welness
    {
        public int? Id { get; set; }
        public int user_id { get; set; }
        public double sleep { get; set; }
        public string mood { get; set; }
        public System.DateTime date { get; set; }
    }
}
